In [17]:
import pandas as pd

In [19]:
trains = pd.read_csv("../data/busesData.csv.crdownload",on_bad_lines='skip', sep='|')
trains.head()

,OperatorId,operator_nm,ClusterId,cluster_nm,OperatorLineId,OfficeLineId,Direction,LineAlternative,Viechle_num,TripId,trip_dt,trip_time,trip_month,trip_day_in_week,bitzua_history_start_dt,bitzua_history_end_dt,erua_hachraga_ind
0,5,דן,11,תל אביב,5.0,25005,2,0,53126703.0,0,2024-03-29,09:04,3,6,2024-03-29 09:04:00,2024-03-29 10:06:20,0.0
1,5,דן,11,תל אביב,9.0,55009,1,0,17775803.0,0,2024-03-29,09:10,3,6,2024-03-29 09:13:16,2024-03-29 09:46:28,0.0
2,5,דן,11,תל אביב,242.0,14242,1,0,54061101.0,0,2024-03-31,09:18,3,1,2024-03-31 09:19:01,2024-03-31 10:00:30,0.0
3,5,דן,11,תל אביב,92.0,24092,1,6,9261201.0,0,2024-03-31,20:40,3,1,2024-03-31 20:40:21,2024-03-31 22:04:26,0.0
4,5,דן,11,תל אביב,242.0,14242,2,0,54061101.0,0,2024-03-31,07:40,3,1,2024-03-31 07:43:27,2024-03-31 08:31:03,0.0

In [11]:
trains_filtred = trains[trains['shana'] > 2020].sort_values(by=['shana'], ascending=False)
trains_filtred.head()

,shana,hodesh,train_trip_cd,first_train_station_nm,last_train_station_nm,rishui_all,rishui_only,bitzua_only,ahuz_bitzua
137869,2025,6,9706,"נתבג""",הרצליה,2,2,0,0.00
137851,2025,6,8833,באר שבע צפון,דימונה,1,1,0,0.00
137873,2025,6,9710,"נתבג""",הרצליה,3,2,0,33.33
137872,2025,6,9709,הרצליה,"נתבג""",3,3,0,0.00
137871,2025,6,9708,"נתבג""",הרצליה,2,2,0,0.00

In [8]:
flights['CHPTOL'] = pd.to_datetime(flights['CHPTOL'], errors='coerce')
flights['CHPTOL'].head()

0   2025-06-18 10:15:00
1   2025-06-18 10:26:00
2   2025-06-18 10:30:00
3   2025-06-18 10:40:00
4   2025-06-18 10:50:00
Name: CHPTOL, dtype: datetime64[ns]

In [9]:
flights['year'] = flights['CHPTOL'].dt.year

In [10]:
flights.set_index('year', inplace=True)
flights.head()

,CHOPER,CHFLTN,CHOPERD,CHSTOL,CHPTOL,CHAORD,CHLOC1,CHLOC1D,CHLOC1TH,CHLOC1T,CHLOC1CH,CHLOCCT,CHTERM,CHCINT,CHCKZN,CHRMINE,CHRMINH
year,,,,,,,,,,,,,,,,,
2025,LY,5132,EL AL ISRAEL AIRLINES,2025-06-18T10:15:00,2025-06-18 10:15:00,A,LCA,LARNACA,לרנקה,LARNACA,קפריסין,CYPRUS,3,NaN,NaN,CANCELED,מבוטלת
2025,LY,5442,EL AL ISRAEL AIRLINES,2025-06-18T08:00:00,2025-06-18 10:26:00,A,LCA,LARNACA,לרנקה,LARNACA,קפריסין,CYPRUS,3,NaN,NaN,LANDED,נחתה
2025,DIR,2032,FLYYO,2025-06-18T10:30:00,2025-06-18 10:30:00,A,HER,HERAKLION,הרקליון,HERAKLION,יוון,GREECE,3,NaN,NaN,CANCELED,מבוטלת
2025,BZ,752,BLUE BIRD AIRWAYS,2025-06-18T10:40:00,2025-06-18 10:40:00,D,HER,HERAKLION,הרקליון,HERAKLION,יוון,GREECE,3,NaN,NaN,CANCELED,מבוטלת
2025,6H,582,ISRAIR AIRLINES,2025-06-18T10:50:00,2025-06-18 10:50:00,A,LCA,LARNACA,לרנקה,LARNACA,קפריסין,CYPRUS,3,NaN,NaN,CANCELED,מבוטלת