In [33]:
import pandas as pd

In [34]:
trains = pd.read_csv("../data/trainsData.csv", sep='|')
trains.head()

,shana,hodesh,train_trip_cd,first_train_station_nm,last_train_station_nm,rishui_all,rishui_only,bitzua_only,ahuz_bitzua
0,2015,1,1,נהריה,"נתבג""",21,0,0,100.0
1,2015,1,2,"נתבג""",נהריה,21,0,0,100.0
2,2015,1,3,נהריה,"נתבג""",21,0,0,100.0
3,2015,1,4,"נתבג""",נהריה,21,0,0,100.0
4,2015,1,5,נהריה,"נתבג""",21,0,0,100.0

In [35]:
trains = trains.copy()

In [36]:
trains.columns = (
        trains.columns
        .str.strip()
        .str.lower()
        .str.replace(' ', '_')
        .str.replace('"', '')
    )

In [37]:
column_rename_map = {
    "shana": "year",
    "hodesh": "month",
    "train_trip_cd": "trip_id",
    "first_train_station_nm": "origin_station",
    "last_train_station_nm": "destination_station",
    "rishui_all": "total_registered",
    "rishui_only": "registered_only",
    "bitzua_only": "executed_only",
    "ahuz_bitzua": "execution_rate"
    }

trains.rename(columns=column_rename_map, inplace=True)

In [38]:
trains = trains.copy()

In [39]:
trains['date'] = pd.to_datetime(trains['year'].astype(str) + '-' + trains['month'].astype(str), format='%Y-%m')

In [40]:
monthly_execution_rate = trains.groupby('date')['execution_rate'].mean().reset_index()

In [41]:
monthly_execution_rate.set_index('date')

            execution_rate
date
2015-01-01       99.103398
2015-02-01       97.409950
2015-03-01       95.465542
2015-04-01       89.442839
2015-05-01       93.037972
...                    ...
2025-02-01       99.836507
2025-03-01       99.940197
2025-04-01       99.597305
2025-05-01       98.843021
2025-06-01       43.808956

[122 rows x 1 columns]