In [2]:
import pandas as pd

In [14]:
trains = pd.read_csv("../data/trainData.csv", sep='|')
trains.head()

,shana,hodesh,train_trip_cd,first_train_station_nm,last_train_station_nm,rishui_all,rishui_only,bitzua_only,ahuz_bitzua
0,2015,1,1,נהריה,"נתבג""",21,0,0,100.0
1,2015,1,2,"נתבג""",נהריה,21,0,0,100.0
2,2015,1,3,נהריה,"נתבג""",21,0,0,100.0
3,2015,1,4,"נתבג""",נהריה,21,0,0,100.0
4,2015,1,5,נהריה,"נתבג""",21,0,0,100.0

In [15]:
trains = trains.copy()

In [16]:
trains['date'] = pd.to_datetime(trains['shana'].astype(str) + '-' + trains['hodesh'].astype(str), format='%Y-%m')
trains['date'].head()

0   2015-01-01
1   2015-01-01
2   2015-01-01
3   2015-01-01
4   2015-01-01
Name: date, dtype: datetime64[ns]

In [22]:
grouped = trains.groupby('date')['ahuz_bitzua'].mean().reset_index()
grouped.set_index('date', inplace=True)
grouped.head(15)

            ahuz_bitzua
date
2015-01-01    99.103398
2015-02-01    97.409950
2015-03-01    95.465542
2015-04-01    89.442839
2015-05-01    93.037972
2015-06-01    98.496667
2015-07-01    99.264774
2015-08-01    99.254993
2015-09-01    97.345565
2015-10-01    98.209298
2015-11-01    98.956404
2015-12-01    98.769927
2016-01-01    99.615952
2016-02-01    99.760533
2016-03-01    99.777557

In [27]:
grouped[grouped.index.year == 2023]

            ahuz_bitzua
date
2023-01-01    99.804313
2023-02-01    99.255751
2023-03-01    99.297216
2023-04-01    90.587881
2023-05-01    92.717537
2023-06-01    96.816494
2023-07-01    98.610384
2023-08-01    99.761261
2023-09-01    94.197327
2023-10-01    86.420645
2023-11-01    99.158484
2023-12-01    99.888656